export const TELLER_SELECT_CARD = 'TELLER_SELECT_CARD';
export const GUESSER_SELECT_CARD = 'GUESSER_SELECT_CARD';
export const GUESSER_WAITING = 'GUESSER_WAITING';
export const SELECT_CARD = 'SELECT_CARD';
